api/urls.py
from django.urls import path
from api.views import api_home, api_groups,api_contributors
urlpatterns = [
    path('', api_home, name = 'api_home'),
    path("groups/", api_groups, name="api_groups"),
    path("C-<pkid>/contributors/", api_contributors, name="api_contributors")
]

saaco/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from app.views import error_404,error_500, register, offline,about,terms, policy,contact
from django.views.generic import TemplateView


urlpatterns = [
    path('', include('app.urls')),
    #ALL AUTH
    path('accounts/', include('allauth.urls')),
    
    # LOCAL URLS
    path("api/", include('api.urls')),
    path('admin/', admin.site.urls),
    path("user/register/", register, name="register"),
    path("user/", include('django.contrib.auth.urls')), 
    # PWA

    path('sw.js', (TemplateView.as_view(template_name="pwa/sw.js", 
          content_type='application/javascript', )), name='sw.js'),
    path("offline/", offline, name="offline")
]+[

    path('about', about, name = 'about'),
    path('contact', contact, name = 'contact'),
    path('terms', terms, name = 'terms'),
    path('policy', policy, name = 'policy'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404
handler500 = error_500

app/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.urls import reverse
from app.services import idshortener

class Profile(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE)
    dp = models.ImageField( upload_to="profile_images", blank = True)
    country = models.CharField(max_length=100, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=13, blank=True)
    time = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = ("Profile")
        verbose_name_plural = ("Profiles")

    def __str__(self):
        return self.name.username

    def get_absolute_url(self):
        return reverse("UserProfile_detail", kwargs={"pk": self.pk})

class Group(models.Model):
    """Model definition for Group."""
    name = models.CharField(max_length=100)
    description = models.TextField( null=True, blank=True)
    img = models.ImageField(upload_to='group_icons', null=True, blank=True)
    members = models.ManyToManyField( User, through='Membership')
    
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    pkid = models.CharField(max_length=11, unique=True, null=False, blank = True)

    class Meta:
        ordering = ['-date']
        """Meta definition for Group."""

        verbose_name = 'Group'
        verbose_name_plural = 'Groups'

    def __str__(self):
        return self.name
    
    def memberscount(self):
        return self.membership_set.count()
    
    def contributioncount(self):
        contributions =  Contribution.objects.filter(group=self).count()
        return contributions

    def save(self,*args, **kwargs):
        try:
            self.pkid = idshortener()
        except: 
           raise ValueError('Could not generate KPID') 
        
        super(Group, self).save(*args, **kwargs)

    def get_absolute_url(self):
        """Return absolute url for Group."""
        return ('')


class Membership(models.Model):
    """Model definition for Membership."""
    group = models.ForeignKey(Group, on_delete= models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    accepted =  models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    phone =  models.CharField(max_length=13, blank =  True, null =  True)


    # TODO: Define fields here

    class Meta:
        ordering = ['date']
        unique_together = [['user', 'group']]
        """Meta definition for Membership."""

        verbose_name = 'Membership'
        verbose_name_plural = 'Memberships'

    def __str__(self):
        return f'{self.user.username}, {self.group.name}'
    def save(self,*args, **kwargs):
        try:
            if self.group.members.count() == 0:
                self.admin = True
                self.accepted = True
            else: pass
        except: 
           raise ValueError('ERROR') 
        
        super(Membership, self).save(*args, **kwargs)
    

    def get_absolute_url(self):
        """Return absolute url for Membership."""
        return ('')

class Contribution(models.Model):
    def default_json():
        return {'total': 0, 'contributors': []}

    pkid = models.CharField(max_length=11, blank=True)
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    contribution_type = models.CharField(max_length=20, default='Other')
    img = models.ImageField(upload_to='contributions', null= True, blank=True)
    budget = models.DecimalField(decimal_places = 2, max_digits=12,  default=0.00)
    contact = models.CharField(max_length=50)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    status = models.BooleanField( default= True)
    collected = models.DecimalField( max_digits=12, decimal_places=2, default=0.00)

    jsondata = models.JSONField(default = default_json, blank = True)#{'Calvin Abunga':2300, 'Mark': 4000, 'Hillary': 20000}

    time = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now =  True)

    class Meta:
        ordering = ['-time']
        verbose_name = ("Contribution")
        verbose_name_plural = ("Contributions")

    def __str__(self):
        return self.title
    
    
    def contributors(self):
        try: list_ = len(self.jsondata['contributors'])
        except: list_ = 0
        return list_

    def percentage(self): 
        percent = 0.00
        try:
            if budget == 0.00 : percent = 0.00
            else:
                percent = round((self.collected/self.budget)*100, 2)
        except:
            percent = 0.00
            
        return percent

    def save(self,*args, **kwargs):
        if not self.pkid:
            try:
                self.pkid = idshortener()
            except: 
               raise ValueError('Could not generate PKID') 
        # print(self.pkid)
        
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("Contribution_detail", kwargs={"pk": self.pk})


class Contributor(models.Model):
    """Model definition for Contributor."""
    name  = models.ForeignKey(User, on_delete=models.CASCADE)
    contributing_to = models.ForeignKey(Contribution,  on_delete=models.CASCADE)
    amount = models.DecimalField( max_digits=10, decimal_places=2, default=0.0)
    paid = models.BooleanField(default=True)

    time = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now =  True)


    # TODO: Define fields here

    class Meta:
        ordering = ['-time']

        unique_together = [['name', 'contributing_to']]
        """Meta definition for Contributor."""

        verbose_name = 'Contributor'
        verbose_name_plural = 'Contributors'

    def __str__(self):
        return f'{self.name.username}, {self.contributing_to.title}'

    def save(self,*args, **kwargs):        
        try: 
            # print(self.contributing_to.group)
            group =  self.contributing_to.group
            # from saaco.models import Membership
            membership = Membership.objects.filter(group = group, user = self.name).exists()
            # print(membership)
            if membership: 
                # Data that we need 
                from decimal import Decimal
                contribution = self.contributing_to
                current_total = contribution.collected
                pk = self.name.pk
                name = f'{self.name.first_name} {self.name.last_name}'
                print(self.name.username)
                amount = Decimal(self.amount)
                contributor_data = { "pk":pk, "name":name, "amount": str(amount) }
                total = current_total+amount
                try: 
                    # Do the contribution update and contributor saving
                    # Save contributor'''
                    super(Contributor, self).save(*args, **kwargs)

                    # Prepare the contribution Data
                    contribution.jsondata["total"] = str(total)
                    contribution.jsondata["contributors"].append(contributor_data)
                    jsondata = {
                        "total": contribution.jsondata["total"],
                        "contributors": contribution.jsondata["contributors"]
                    }
                    # Then use the Data to update  the contribution
                    Contribution.objects.filter(pkid = self.contributing_to.pkid).update( collected = total, jsondata = jsondata)

                except Exception as e:  raise  Exception(f"Could not save the item in question, try again, Error: {e}")

            else: raise Exception('Contributor Doesnt Exist')  

        except: raise Exception(f'User {self.name} Doesnt Belong To The Group {group}')         
        # super(Contributor, self).save(*args, **kwargs)

    # def save(self, *args, **kwargs):        
    #     try: 
    #         group = self.contributing_to.group
    #         # Check if the user is a member of the group
    #         membership = Membership.objects.filter(group=group, user=self.name).exists()
    #         if membership: 
    #             # If the user is a member, proceed with saving the contribution data
    #             contribution = self.contributing_to
    #             current_total = contribution.collected
    #             pk = self.name.pk
    #             name = f'{self.name.first_name} {self.name.last_name}'
    #             amount = self.amount
    #             contributor_data = {"pk": pk, "name": name, "amount": amount}

    #             # Update contribution data
    #             contribution.jsondata["total"] = current_total + amount
    #             contribution.jsondata["contributors"].append(contributor_data)
    #             contribution.collected = contribution.jsondata["total"]
    #             # Save contribution
    #             contribution.save()

    #             # Save contributor
    #             super(Contributor, self).save(*args, **kwargs)
    #         else:
    #             # If the user is not a member, raise an exception
    #             raise Exception('Contribution Doesnt Exist')  
    #     except Exception as e:
    #         # Catch any exceptions and raise a generic exception
    #         raise Exception("Could not save the item in question. Error: {}".format(str(e)))




        

app/forms.py
from django import forms
# from rest_framework.validators import UniqueValidator
from django.contrib.auth.models import User
from .models import Group, Membership, Contribution, Contributor

# class UniqueEmailValidator(UniqueValidator):
#     def filter_queryset(self, value, queryset):
#         return queryset.filter(email=value)

# class UniqueUsernameValidator(UniqueValidator):
#     def filter_queryset(self, value, queryset):
#         return queryset.filter(username=value)

class RegistrationForm(forms.Form):
    email = forms.EmailField()
    username = forms.CharField()
    first_name = forms.CharField()
    last_name =forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class GroupForm(forms.ModelForm):
    item = forms.CharField(required=True, widget= forms.HiddenInput(attrs = {'value': 'group'}))
    name =  forms.CharField(required = True, widget=forms.TextInput(attrs={ 'class': 'input is-medium ', 'placeholder':'Group Name'}))

    class Meta:
        model = Group
        fields = ("name",)

class ContributionForm(forms.ModelForm):   
    EDUCATION = 'Education'
    BUSINESS = 'Business'
    CHAMA = 'Chama'
    MEDICAL = 'Medical'
    RELIGIOUS = 'Religious'
    WEDDING = 'Wedding'
    FUNERAL = 'Funeral'
    OTHER = 'Other'

    CONTRIBUTION_TYPE_CHOICES = [
        (EDUCATION, 'Education'),
        (BUSINESS, 'Business'),
        (CHAMA, 'Chama'),
        (MEDICAL, 'Medical'),
        (RELIGIOUS, 'Religious'),
        (WEDDING, 'Wedding'),
        (FUNERAL, 'Funeral'),
        (OTHER, 'Other'),
    ]
    item = forms.CharField(required= True,widget=forms.HiddenInput(attrs = {'value': 'contribution'}))
    title =  forms.CharField(required = True, widget=forms.TextInput(attrs={ 'class': 'is-normal input', 'placeholder':'Title Of Your Contribution'}))
    description = forms.CharField(required=True, widget =forms.Textarea(attrs={
        'class': 'textarea ',
        'rows' : '2',
        'placeholder':'Write a Good Summary About your Contribution'})
    )
    contribution_type = forms.ChoiceField(
        choices=CONTRIBUTION_TYPE_CHOICES,
        required=True
    )
    # group = forms.ChoiceField( required=True)
    
    class Meta:
        model = Contribution
        fields = ("title","description",'contribution_type','group', "budget", )


class ContributorForm(forms.Form):
    pk = forms.CharField(required=False,widget=forms.HiddenInput())
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={ 'class': 'is-medium input', 'placeholder':'Contributor\'s Name'}))
    amount = forms.CharField(required = True, widget=forms.NumberInput(attrs={ 'class': 'is-medium input', 'placeholder':'Amount'}) )

templates/app/add.html
{% extends 'base.html' %}

{% block content %}
<style>
    .hero{
        justify-content: flex-start !important;
    }
    .item-title{
        font-size: 1.5rem;
        color: #363636;
    }
    .background-transparent{
        background-color: transparent !important;
    }
    .icon.round{
        border-radius: 50%;
        background: var(--primary-color);
        width: 48px;
        height: 48px;
        color: white;
        padding: 2.0rem;
    }
    .group-popup{
        display: flex;
        position: absolute;
        z-index: 10000;
        padding: 1.5rem;
        width: 100vw;
        height: 100vh;
        top: 0;
        left: 0;
        right: 0;
        flex-direction: column;
        justify-content: center;
    }
    .form-close{
        position: absolute;
        top: 2rem;
    }
</style>
<section class="hero has-background-white-ter is-fullheight-with-navbar">
    <nav class="primary-bg mb-0">
    <div class="container">
        <div class="tabs is-medium">
            <ul>
                <li class="is-active">  
                    <a href="{% url 'home' %}" class="has-text-white">       
                        <span class="icon"><i class="fa fa-arrow-left"></i> 
                        </span>
                        <strong  class="has-text-white">
                            /Create  
                            {% if item %}
                                {{item}}
                            {% else %}
                                Group or Contribution
                            {% endif %}
                                
                        </strong>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    </nav>
    <div class="m-0 p-1"> 
            
            {% if form %}  

                <form action="/{{item|lower}}s/" method="POST" class="container form p-3">               
                    {% csrf_token %}
                    {{form.item}}
                    <div class="field">
                        <label for="name" class="label ">{% if form.name %} Name {% else %} Title {% endif %}</label>
                        <div class="control">
                            {{form.name}} {{form.title}}
                        </div>
                    </div>

                    {% if item == 'Contribution'%}
                    
                    <div class="field">
                        <label for="description" class="label">Message</label>
                        <div class="control">
                            {{form.description}}
                        </div>
                    </div>
                    
                    <div class="field">
                        <label for="contribution_type" class="label">Contribution Type</label>
                        <div class="select">
                            <select name="contribution_type" id="id_contribution_type">
                              <option class="option" value="" selected="">Chose Contribution Type</option>  
                              <option value="Education">Education (School Feess)</option>
                              <option value="Business">Business (Capital Fund Raiser)</option>
                              <option value="Chama">Chama (Group Fund)</option>
                              <option value="Medical">Medical Bill</option>
                              <option value="Religious">Religious</option>
                              <option value="Wedding">Wedding</option>
                              <option value="Funeral">Funeral</option>
                              <option value="Other">Other</option>
                            </select>
                        </div>
                    </div>


                    <div  class="field">
                        <label for="group" class="label">Group <span id="showFlashForm" class="icon"><i class="fa fa-add has-text-success"></i></span> </label>
                        <div class="select">
                            <select  name="group" required="" id="id_group">
                                <option class="option" value="" selected="">Chose a Group</option>
                                {% for item in admin %}  
                                    <option class="option" value="{{item.group.pk}}">{{item.group.name}}</option>                                
                                {% endfor %} 
                            </select>
                        </div>
                    </div>
                    <div class="field">
                        <label for="budget" class="label">Target</label>
                        <div class="control">
                            <input type="number" name="budget" value="00" class="input" required="" id="id_budget">
                        </div>
                    </div> 

                        
                    {% endif %}
                                       
                    <button class="button primary-bg is-medium is-fullwidth">
                        <span>Next</span>
                        <span class="icon is-small">
                            <i class="fas fa-chevron-right"></i>
                        </span>
                    </button>
                </form>

            {% else %}

                <div class="container pt-6 p-4">
                    <div class="is-fullwidth mb-4 is-medium ">
                        <a href="{% url 'add' %}?item=group" class="creators">
                            <span class="icon mr-2 round">
                                <i class="fa fa-users fa-2x"></i>
                            </span>
                            <span class="has-text-weight-bold is-size-5">Create Group</span>
                        </a>
                    </div>
                    <div class="is-fullwidth is-medium">
                        <a href="{% url 'add' %}?item=contribution" class="creators">
                            <span class="icon mr-2 round">
                                <i class="fa fa-hand-holding-heart fa-2x"></i>
                            </span>
                            <span class="has-text-weight-bold is-size-5">Start Contribution</span>
                        </a>
                    </div>
                </div>              
                
            {% endif %}
    </div>
</section>

<!-- MOdal and message section -->
<div id="modal-success" class="modal">
  <div class="modal-background"></div>

  <div class="modal-content p-5">
    <div class="box notification is-success">
      <p class=" ">Group Creation Success</p>
    </div>
  </div>

  <button class="modal-close is-large" aria-label="close"></button>
</div>
    <!-- Group POPUP -->
    {% if  item == 'Contribution' %}     
        <form method="post" action="{% url 'api_groups' %}" class=" {% if admin %} is-hidden {% endif %} group-popup has-background-white"  id="flashGroupForm"> 
            {% if admin %}<span class="icon form-close" id="formClose" ><i class="fa fa-close fa-2x has-text-black"></i></span>  {% endif %}
            {% csrf_token %}
            <input type="hidden" name="item" value="flash" id="id_item">
            <div class="field" >
                {% if not admin %}
                    <div class="is-flex is-justify-content-center">
                        <span class="icon" ><i class="fa fa-cancel has-text-danger fa-3x"></i></span>
                    </div>                          
                    <p class="subtitle mt-6 mb-6">You can't start a contribution if you're not an admin of any group!</p>
                {% endif %}
                <h1 class="title">Please Create a Group</h1>
                <label for="name" class="label ">Name</label>
                <div class="control">
                    <input type="text" name="name" class="input is-medium " placeholder="Group Name" required="" id="id_name">  
                </div>
            </div>
            <button class="button primary-bg " type ="submit" id="flashSubmit">
                <span>Next</span> 
                <span class="icon"><i class="fa fa-chevron-right"></i></span>
            </button>
        </form>
        <script>
            var showFlashForm = document.querySelector("#showFlashForm")
            var formClose =  document.querySelector("#formClose")
            var flashSubmit = document.querySelector("#flashSubmit")
            let flashGroupForm = document.querySelector("#flashGroupForm");

            async function createFlashGroup() {
                let groupSelect = document.querySelector('#id_group')
                let formData = new FormData(document.querySelector("#flashGroupForm"))
                console.log(formData)
                try {
                  const response = await fetch('/api/groups/', {
                    method: "POST", // or 'PUT'
                    body:formData,
                  });
                  if (!response.ok) {
                    throw new Error("Network response was not OK");
                  }
              
                  const data = await response.json();
                  console.log(data);

                  const option = document.createElement('option');
                  option.value = data.id;
                  option.textContent = data.name;
                  groupSelect.insertBefore(option, groupSelect.firstElementChild.nextSibling);
                  flashGroupForm.reset()
                //   close the form when successfull
                  flashGroupForm.classList.toggle('is-hidden');
                //   Show success modal
                  document.querySelector('.modal').classList.toggle('is-active')


                } catch (error) {
                  console.error("Error:", error);
                }
            };
              

            showFlashForm.addEventListener('click', () => {
                flashGroupForm.classList.toggle('is-hidden');
            });

            flashGroupForm.addEventListener('submit',(e) =>{
                e.preventDefault();
                flashSubmit.classList.toggle('is-loading')
                flashSubmit.setAttribute('disabled','')
                const groupName = document.getElementById('id_name');
                console.log('Trial')

                if (groupName.value.trim()){
                    createFlashGroup()
                }
                else{
                    groupName.classList.toggle('is-danger')
                }
                flashSubmit.classList.toggle('is-loading');
                flashSubmit.removeAttribute('disabled')
                console.log('end')
            })
        </script>
            
        {% if admin %}
            <script>
                //This one to show the close button only when the user an admin
                formClose.addEventListener('click', () => {
                    flashGroupForm.classList.toggle('is-hidden');
                });
            </script>    
        {% endif %}
    {% endif %}
{% endblock content %}
{% block footer %}{% endblock footer %}


{% block script %}
    
{% endblock script %}
    

    